openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Arch Lab Example API"
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8081
    description: Other server
paths:
  /visit:
    post:
      summary: Фиксация визита
      parameters:
        - name: user_id
          description: Идентификатор пользователя
          in: query
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /get_visits:
    get:
      summary: Отдает информацию о пользователях и их времени визита
      responses:
        "200":
          description: Список данных о визитах пользователей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/visits"
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /message:
    get:
      summary: Какой-то интерфейс
      parameters:
        - name: params
          description: какой-то параметр
          in: query
          required: true
          schema:
            type: string

      responses:
        "200":
          description: User ID
          content:
            application/json:
              schema:
                type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    visits:
      description: Список данных о визитах полозователей.
      type: array
      items:
        $ref: "#/components/schemas/visit"

    visit_id:
      description: Уникальный идентификатор визита
      type: integer

    visit:
      description: Информация о конкретном визите.
      type: object
      required:
        - id
        - user_id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
        - datetime
      properties:
        id:
          $ref: "#/components/schemas/visit_id"
        user_id:
          type: string
        datetime:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
